-- begin ECOMMERCE_PAYMENT
alter table ECOMMERCE_PAYMENT add constraint FK_ECOMMERCE_PAYMENT_ON_ORDER foreign key (ORDER_ID) references ECOMMERCE_ORDER(ID)^
create index IDX_ECOMMERCE_PAYMENT_ON_ORDER on ECOMMERCE_PAYMENT (ORDER_ID)^
-- end ECOMMERCE_PAYMENT
-- begin ECOMMERCE_CATEGORY
alter table ECOMMERCE_CATEGORY add constraint FK_ECOMMERCE_CATEGORY_ON_SUB_CATEGORY foreign key (SUB_CATEGORY_ID) references ECOMMERCE_SUB_CATEGORY(ID)^
create index IDX_ECOMMERCE_CATEGORY_ON_SUB_CATEGORY on ECOMMERCE_CATEGORY (SUB_CATEGORY_ID)^
-- end ECOMMERCE_CATEGORY
-- begin ECOMMERCE_PRODUCT
alter table ECOMMERCE_PRODUCT add constraint FK_ECOMMERCE_PRODUCT_ON_CATEGORY foreign key (CATEGORY_ID) references ECOMMERCE_CATEGORY(ID)^
create index IDX_ECOMMERCE_PRODUCT_ON_CATEGORY on ECOMMERCE_PRODUCT (CATEGORY_ID)^
-- end ECOMMERCE_PRODUCT
-- begin ECOMMERCE_ORDER
alter table ECOMMERCE_ORDER add constraint FK_ECOMMERCE_ORDER_ON_SHIP_TO foreign key (SHIP_TO_ID) references ECOMMERCE_ADDRESS(ID)^
create index IDX_ECOMMERCE_ORDER_ON_SHIP_TO on ECOMMERCE_ORDER (SHIP_TO_ID)^
-- end ECOMMERCE_ORDER
-- begin ECOMMERCE_LINE_ITEM
alter table ECOMMERCE_LINE_ITEM add constraint FK_ECOMMERCE_LINE_ITEM_ON_PRODUCT foreign key (PRODUCT_ID) references ECOMMERCE_PRODUCT(ID)^
create index IDX_ECOMMERCE_LINE_ITEM_ON_PRODUCT on ECOMMERCE_LINE_ITEM (PRODUCT_ID)^
-- end ECOMMERCE_LINE_ITEM
