-- begin ECOMMERCE_PAYMENT
alter table ECOMMERCE_PAYMENT add constraint FK_ECOMMERCE_PAYMENT_ON_ORDER foreign key (ORDER_ID) references ECOMMERCE_ORDER(ID)^
create index IDX_ECOMMERCE_PAYMENT_ON_ORDER on ECOMMERCE_PAYMENT (ORDER_ID)^
-- end ECOMMERCE_PAYMENT
-- begin ECOMMERCE_CATEGORY
alter table ECOMMERCE_CATEGORY add constraint FK_ECOMMERCE_CATEGORY_ON_SUB_CATEGORY foreign key (SUB_CATEGORY_ID) references ECOMMERCE_SUB_CATEGORY(ID)^
create index IDX_ECOMMERCE_CATEGORY_ON_SUB_CATEGORY on ECOMMERCE_CATEGORY (SUB_CATEGORY_ID)^
-- end ECOMMERCE_CATEGORY
-- begin ECOMMERCE_PRODUCT
alter table ECOMMERCE_PRODUCT add constraint FK_ECOMMERCE_PRODUCT_ON_CATEGORY foreign key (CATEGORY_ID) references ECOMMERCE_CATEGORY(ID)^
create index IDX_ECOMMERCE_PRODUCT_ON_CATEGORY on ECOMMERCE_PRODUCT (CATEGORY_ID)^
-- end ECOMMERCE_PRODUCT
-- begin ECOMMERCE_ACCOUNT
alter table ECOMMERCE_ACCOUNT add constraint FK_ECOMMERCE_ACCOUNT_ON_CUSTOMER_ACCOUNT foreign key (CUSTOMER_ACCOUNT_ID) references ECOMMERCE_ACCOUNT(ID)^
alter table ECOMMERCE_ACCOUNT add constraint FK_ECOMMERCE_ACCOUNT_ON_PAYMENT foreign key (PAYMENT_ID) references ECOMMERCE_PAYMENT(ID)^
create index IDX_ECOMMERCE_ACCOUNT_ON_CUSTOMER_ACCOUNT on ECOMMERCE_ACCOUNT (CUSTOMER_ACCOUNT_ID)^
create index IDX_ECOMMERCE_ACCOUNT_ON_PAYMENT on ECOMMERCE_ACCOUNT (PAYMENT_ID)^
-- end ECOMMERCE_ACCOUNT
-- begin ECOMMERCE_PHONE
alter table ECOMMERCE_PHONE add constraint FK_ECOMMERCE_PHONE_ON_CUSTOMER foreign key (CUSTOMER_ID) references ECOMMERCE_CUSTOMER(ID)^
create index IDX_ECOMMERCE_PHONE_ON_CUSTOMER on ECOMMERCE_PHONE (CUSTOMER_ID)^
-- end ECOMMERCE_PHONE
-- begin ECOMMERCE_ORDER
alter table ECOMMERCE_ORDER add constraint FK_ECOMMERCE_ORDER_ON_ADDRESS foreign key (ADDRESS_ID) references ECOMMERCE_ADDRESS(ID)^
alter table ECOMMERCE_ORDER add constraint FK_ECOMMERCE_ORDER_ON_ACCOUNT foreign key (ACCOUNT_ID) references ECOMMERCE_ACCOUNT(ID)^
create index IDX_ECOMMERCE_ORDER_ON_ADDRESS on ECOMMERCE_ORDER (ADDRESS_ID)^
create index IDX_ECOMMERCE_ORDER_ON_ACCOUNT on ECOMMERCE_ORDER (ACCOUNT_ID)^
-- end ECOMMERCE_ORDER
-- begin ECOMMERCE_DOCUMENTS
alter table ECOMMERCE_DOCUMENTS add constraint FK_ECOMMERCE_DOCUMENTS_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
alter table ECOMMERCE_DOCUMENTS add constraint FK_ECOMMERCE_DOCUMENTS_ON_ORDER foreign key (ORDER_ID) references ECOMMERCE_ORDER(ID)^
create index IDX_ECOMMERCE_DOCUMENTS_ON_FILE on ECOMMERCE_DOCUMENTS (FILE_ID)^
create index IDX_ECOMMERCE_DOCUMENTS_ON_ORDER on ECOMMERCE_DOCUMENTS (ORDER_ID)^
-- end ECOMMERCE_DOCUMENTS
-- begin ECOMMERCE_LINE_ITEM
alter table ECOMMERCE_LINE_ITEM add constraint FK_ECOMMERCE_LINE_ITEM_ON_PRODUCT foreign key (PRODUCT_ID) references ECOMMERCE_PRODUCT(ID)^
alter table ECOMMERCE_LINE_ITEM add constraint FK_ECOMMERCE_LINE_ITEM_ON_ORDER foreign key (ORDER_ID) references ECOMMERCE_ORDER(ID)^
create index IDX_ECOMMERCE_LINE_ITEM_ON_PRODUCT on ECOMMERCE_LINE_ITEM (PRODUCT_ID)^
create index IDX_ECOMMERCE_LINE_ITEM_ON_ORDER on ECOMMERCE_LINE_ITEM (ORDER_ID)^
-- end ECOMMERCE_LINE_ITEM
-- begin ECOMMERCE_ADDRESS
alter table ECOMMERCE_ADDRESS add constraint FK_ECOMMERCE_ADDRESS_ON_CUSTOMER foreign key (CUSTOMER_ID) references ECOMMERCE_CUSTOMER(ID)^
alter table ECOMMERCE_ADDRESS add constraint FK_ECOMMERCE_ADDRESS_ON_ACCOUNT foreign key (ACCOUNT_ID) references ECOMMERCE_ACCOUNT(ID)^
create index IDX_ECOMMERCE_ADDRESS_ON_CUSTOMER on ECOMMERCE_ADDRESS (CUSTOMER_ID)^
create index IDX_ECOMMERCE_ADDRESS_ON_ACCOUNT on ECOMMERCE_ADDRESS (ACCOUNT_ID)^
-- end ECOMMERCE_ADDRESS
-- begin ECOMMERCE_SHOPPING_CARD
alter table ECOMMERCE_SHOPPING_CARD add constraint FK_ECOMMERCE_SHOPPING_CARD_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_ECOMMERCE_SHOPPING_CARD_ON_USER on ECOMMERCE_SHOPPING_CARD (USER_ID)^
-- end ECOMMERCE_SHOPPING_CARD
-- begin ECOMMERCE_CUSTOMER
alter table ECOMMERCE_CUSTOMER add constraint FK_ECOMMERCE_CUSTOMER_ON_ACCOUNT_CUSTOMER foreign key (ACCOUNT_CUSTOMER_ID) references ECOMMERCE_ACCOUNT(ID)^
alter table ECOMMERCE_CUSTOMER add constraint FK_ECOMMERCE_CUSTOMER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_ECOMMERCE_CUSTOMER_ON_ACCOUNT_CUSTOMER on ECOMMERCE_CUSTOMER (ACCOUNT_CUSTOMER_ID)^
create index IDX_ECOMMERCE_CUSTOMER_ON_USER on ECOMMERCE_CUSTOMER (USER_ID)^
-- end ECOMMERCE_CUSTOMER
