alter table ECOMMERCE_ACCOUNT add constraint FK_ECOMMERCE_ACCOUNT_ON_CUSTOMER_ACCOUNT foreign key (CUSTOMER_ACCOUNT_ID) references ECOMMERCE_ACCOUNT(ID);
alter table ECOMMERCE_ACCOUNT add constraint FK_ECOMMERCE_ACCOUNT_ON_PAYMENT foreign key (PAYMENT_ID) references ECOMMERCE_PAYMENT(ID);
create index IDX_ECOMMERCE_ACCOUNT_ON_CUSTOMER_ACCOUNT on ECOMMERCE_ACCOUNT (CUSTOMER_ACCOUNT_ID);
create index IDX_ECOMMERCE_ACCOUNT_ON_PAYMENT on ECOMMERCE_ACCOUNT (PAYMENT_ID);
