alter table ECOMMERCE_LINE_ITEM add constraint FK_ECOMMERCE_LINE_ITEM_ON_ORDER foreign key (ORDER_ID) references ECOMMERCE_ORDER(ID);
create index IDX_ECOMMERCE_LINE_ITEM_ON_ORDER on ECOMMERCE_LINE_ITEM (ORDER_ID);
