alter table ECOMMERCE_CUSTOMER add constraint FK_ECOMMERCE_CUSTOMER_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_ECOMMERCE_CUSTOMER_ON_USER on ECOMMERCE_CUSTOMER (USER_ID);
