alter table ECOMMERCE_LINE_ITEM add constraint FK_ECOMMERCE_LINE_ITEM_ON_PRODUCT foreign key (PRODUCT_ID) references ECOMMERCE_PRODUCT(ID);
create index IDX_ECOMMERCE_LINE_ITEM_ON_PRODUCT on ECOMMERCE_LINE_ITEM (PRODUCT_ID);
