alter table ECOMMERCE_SHOPPING_CARD add constraint FK_ECOMMERCE_SHOPPING_CARD_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_ECOMMERCE_SHOPPING_CARD_ON_USER on ECOMMERCE_SHOPPING_CARD (USER_ID);
