alter table ECOMMERCE_ORDER add constraint FK_ECOMMERCE_ORDER_ON_ADDRESS foreign key (ADDRESS_ID) references ECOMMERCE_ADDRESS(ID);
create index IDX_ECOMMERCE_ORDER_ON_ADDRESS on ECOMMERCE_ORDER (ADDRESS_ID);
