alter table ECOMMERCE_DOCUMENTS add constraint FK_ECOMMERCE_DOCUMENTS_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID);
alter table ECOMMERCE_DOCUMENTS add constraint FK_ECOMMERCE_DOCUMENTS_ON_ORDER foreign key (ORDER_ID) references ECOMMERCE_ORDER(ID);
create index IDX_ECOMMERCE_DOCUMENTS_ON_FILE on ECOMMERCE_DOCUMENTS (FILE_ID);
create index IDX_ECOMMERCE_DOCUMENTS_ON_ORDER on ECOMMERCE_DOCUMENTS (ORDER_ID);
