alter table ECOMMERCE_ADDRESS add constraint FK_ECOMMERCE_ADDRESS_ON_CUSTOMER foreign key (CUSTOMER_ID) references ECOMMERCE_CUSTOMER(ID);
create index IDX_ECOMMERCE_ADDRESS_ON_CUSTOMER on ECOMMERCE_ADDRESS (CUSTOMER_ID);
