alter table ECOMMERCE_ADDRESS add constraint FK_ECOMMERCE_ADDRESS_ON_ACCOUNT foreign key (ACCOUNT_ID) references ECOMMERCE_ACCOUNT(ID);
create index IDX_ECOMMERCE_ADDRESS_ON_ACCOUNT on ECOMMERCE_ADDRESS (ACCOUNT_ID);
