alter table ECOMMERCE_PHONE add constraint FK_ECOMMERCE_PHONE_ON_CUSTOMER foreign key (CUSTOMER_ID) references ECOMMERCE_CUSTOMER(ID);
create index IDX_ECOMMERCE_PHONE_ON_CUSTOMER on ECOMMERCE_PHONE (CUSTOMER_ID);
